### ISSUE TITLE
Not able to add this plugin on acquia cms project.

### ISSUE THREAD

**Issue by kuntal15** [acquia/blt-drupal-test#5]
Hi,

I have used acquia/drupal-recommended-project template to create a project.

Here it comes with phpunit version 9.5.9.

I am not able to add this plugin in my project.

Thanks,

**Comment by danepowell** [comment]
I think you just need to require the plugin adding the `--with-all-dependencies` argument: https://github.com/acquia/blt-drupal-test/commit/a61788ccae08f61857b83361028c8457de2b1dc9

**Comment by kuntal15** [comment]
Thanks. It works.
